### PR TITLE
Add support for symlinked sources

### LINKED ISSUE #28: Source Files in Linked Directories
see comment below for my point.

### PR DESCRIPTION
**Pull request by melissawm**
Hopefully, closes #28 :tada:

@kassbohm would you please test this to see if it solves your problem? 

Thanks!

### CODE REVIEW

**Comment by melissawm** [comment]
@kassbom I think it was one path resolution that was in the wrong place - can you check now? Thanks!

**Comment by kassbohm** [comment]
@melissawm I did check. As far as I see: It is working now. Thanks!

So is this going to be used also in the main branch later on?

Btw: Your documentation says **tags_create_tags** - Whether to process tags or not. **Default: True**. I think, this isn't **True**, but **False**.

**Review by kassbohm — COMMENTED** [review]
I think it's correct now.

**Comment by melissawm** [comment]
Yes, I will merge this (perhaps with your suggestion) and with one more PR I will do a 0.2 release, but this particular PR should be on main later today. Thanks!

**Comment by melissawm** [comment]
In it goes!

**Pull request merged**
