### PR TITLE
Add automated tests

### LINKED ISSUE #38: Add tests
For now, the documentation itself serves as tests for the current features, but this doesn't test (for example) the use of symlinked directories. We should have a proper test suite for the extension.

### PR DESCRIPTION
**Pull request by JWCook**
Closes #38

### Test setup
* Added structure for a test suite using the [sphinx.testing](https://github.com/sphinx-doc/sphinx/tree/master/sphinx/testing) plugin
    * I added some notes in `conftest.py` on how the tests are set up, but let me know if any of that doesn't make sense.
    * I think the least obvious part is how input directories are passed to `SphinxTestApp` (via a pytest fixture and a marker). That's how [Sphinx's own tests](https://github.com/sphinx-doc/sphinx/tree/master/tests) do it, but it seems potentially confusing.
* Run tests in CircleCI
* A test coverage report is generated in the CI job and also output to the console.
    * If you wanted to, you could send this coverage report to [Codecov](https://codecov.io) (or a similar site) and enable PR integration
    * You could also add a [coverage badge](https://shields.io/badges/codecov) to your readme if you'd like, and show off your shiny new 98% coverage :)

### Coverage
Test coverage has been added for:
* Tags with emoji, spaces, and other special characters
* Tags in subdirectories
* Symlinked files and directories
* Jupyter notebooks
* Tagged pages (text output of `tags` directive)
* Badges
  * Badge colors
* Sources excluded by `exclude_patterns`

### CODE REVIEW

**Comment by JWCook** [comment]
@melissawm I believe this PR is ready to go. This depends on merging #57 first, so once that's done I can rebase this one.

**Comment by JWCook** [comment]
I rebased this on top of main, so this is ready to go.

**Comment by melissawm** [comment]
Running pytest on this with Python 3.12, Sphinx 7.2.6, pytest 7.4.3 I get

```
  /home/melissa/projects/sphinx-tags/test/conftest.py:18: RemovedInSphinx90Warning: 'sphinx.testing.path' is deprecated. Use 'os.path' or 'pathlib' instead.
```

This is not a blocker though - we could put this in and deal with the deprecation later.

**Comment by JWCook** [comment]
Hmm, I originally tried `pathlib`, but using `sphinx.testing.path` seemed to be required for Sphinx<=6. You can create another issue for that if you want, and I can look into it some more later.

**Comment by melissawm** [comment]
I'm not going to say I understand all details but I do get the overall idea and I see zero reasons to hold this off - thank you so much for being patient and sticking with it! I have a few more details to sort and should be cutting a release later this weekend. Cheers!

**Pull request merged**
